service: pet-project

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-northeast-1
  memorySize: 1024
  timeout: 60

# plugins: -serverless-offline

# functions:
#   api:
#     handler: src/server/serverless.handler
#     events:
#       - http:
#           path: api/{proxy+}
#           method: ANY
#           cors: true

# Create DynamoDB
resources:
  Resources:
    # Tạo S3 bucket
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: linh-s3-bucket
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
              AllowedHeaders:
                - "*"

    # Bảng Users
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH" # Primary Key
        # GlobalSecondaryIndexes:
        #   - IndexName: "EmailIndex"
        #     KeySchema:
        #       - AttributeName: "email"
        #         KeyType: "HASH"
        #     Projection:
        #       ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # Bảng Posts
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PostsTable
        AttributeDefinitions:
          - AttributeName: "postId"
            AttributeType: "S"
          # - AttributeName: "user_email"
          #   AttributeType: "S"
        KeySchema:
          - AttributeName: "postId"
            KeyType: "HASH" # Primary Key
        # GlobalSecondaryIndexes:
        #   - IndexName: "UserEmailIndex"
        #     KeySchema:
        #       - AttributeName: "user_email"
        #         KeyType: "HASH"
        #     Projection:
        #       ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
